# Generated by Django 5.2.7 on 2026-01-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
    ]
